# -*- coding: utf-8 -*-
"""обработка+eda_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LH5yTBOT2UhRPj6a33xs2XB7pX4ncp6f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.sparse import coo_matrix

"""# Обработка данных

## FLIGHTS
"""

flights = pd.read_csv('/content/flights.csv', sep=",")
print(flights.info())
flights.head(3)

print("Пропуски по столбцам:")
print(flights.isnull().sum())

print("Дубли строк:", flights.duplicated().sum())
print("Дубли flight_id:", flights['flight_id'].duplicated().sum())

print("Уникальные значения 'Операционный перевозчик':")
print(sorted(flights["Операционный перевозчик"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(flights["Операционный перевозчик"].value_counts(dropna=False))

print("Уникальные значения 'Город вылета':")
print(sorted(flights["Город вылета"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(flights["Город вылета"].value_counts(dropna=False)[:3])

print("Уникальные значения 'Город прилета':")
print(sorted(flights["Город прилета"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(flights["Город прилета"].value_counts(dropna=False)[:3])

print("Уникальные значения 'Аэропорт вылета':")
print(sorted(flights["Аэропорт вылета"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(flights["Аэропорт вылета"].value_counts(dropna=False)[:3])

print("Уникальные значения 'Аэропорт прилета':")
print(sorted(flights["Аэропорт прилета"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(flights["Аэропорт прилета"].value_counts(dropna=False)[:3])

flights['Дата вылета'] = pd.to_datetime(flights['Дата вылета'], utc=True, errors='coerce')

print("ТИПЫ ДАННЫХ")
print(flights.dtypes)

"""## PASSENGERS"""

passengers = pd.read_csv('/content/passengers.csv', sep=",")
print(passengers.info())
passengers.head(3)

print("Пропуски по столбцам:")
print(passengers.isnull().sum())

print("Дубли строк:", passengers.duplicated().sum())
print("Дубли passenger_id:", passengers['passenger_id'].duplicated().sum())

print("Уникальные значения 'Пол':")
print(sorted(passengers["Пол"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(passengers["Пол"].value_counts(dropna=False))

passengers['Дата рождения'] = pd.to_datetime(passengers['Дата рождения'], errors='coerce')

passengers['Пол'] = passengers['Пол'].map({'F': 0, 'M': 1})

print("Типы данных:")
print(passengers.dtypes)

"""## BOOKINGS"""

bookings = pd.read_csv('/content/bookings.csv', sep=",")
print(bookings.info())
bookings.head(3)

bookings = bookings.replace("\\N", np.nan)

print("Пропуски по столбцам:")
print(bookings.isnull().sum())

pair_duplicates = bookings.duplicated(subset=["passenger_id", "flight_id"]).sum()
print("Количество дубликатов по паре passenger_id + flight_id:", pair_duplicates)

duplicate_pairs = bookings[bookings.duplicated(subset=["passenger_id", "flight_id"], keep=False)] \
    .sort_values(["passenger_id", "flight_id"])

print("\nПримеры дублирующихся пар passenger_id + flight_id:")
duplicate_pairs.head(4)

bookings = bookings.sort_values(
    by=['passenger_id', 'flight_id', 'Статус билета пассажира'],
    ascending=[True, True, False],
    na_position='last'
)

bookings = bookings.drop_duplicates(
    subset=['passenger_id', 'flight_id'],
    keep='first'
).reset_index(drop=True)

bookings[(bookings['passenger_id'] == 7336219221304344578) & (bookings['flight_id'] == 13783)]

print("Пропуски по столбцам:")
print(bookings.isnull().sum())

missing_status = bookings[bookings['Статус билета пассажира'].isna()]
print('Пропущено строк:', len(missing_status))
missing_status

bookings[bookings['passenger_id'] == 7335643970564587523]

bookings['Статус билета пассажира'] = bookings['Статус билета пассажира'].fillna('OK')

print("Пропуски по столбцам:")
print(bookings.isnull().sum())

print("Уникальные значения 'Статус билета пассажира':")
print(sorted(bookings["Статус билета пассажира"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(bookings["Статус билета пассажира"].value_counts(dropna=False))

print("Уникальные значения 'Класс бронирования':")
print(sorted(bookings["Класс бронирования"].dropna().astype(str).unique().tolist()))

print("\nЧастоты статусов:")
print(bookings["Класс бронирования"].value_counts(dropna=False)[:3])

bookings['Дата бронирования'] = pd.to_datetime(bookings['Дата бронирования'], errors='coerce')
bookings['Дата бронирования'] = bookings['Дата бронирования'].dt.tz_convert('UTC')

print("Тип:", bookings['Дата бронирования'].dtype)

print("Типы данных после исправления:")
print(bookings.dtypes)

"""## ОБЪЕДИНЕНИЕ"""

# bookings + flights
bookings_flights = bookings.merge(
    flights,
    on='flight_id',
    how='left',
    validate='many_to_one'
)

# + passengers
df_final = bookings_flights.merge(
    passengers,
    on='passenger_id',
    how='left',
    validate='many_to_one'
)

print("Размер итоговой таблицы:", df_final.shape)
df_final.head(3)

print("ПРОВЕРКА КОРРЕКТНОСТИ")

# Сравнение количества строк
print("Строк в bookings:", len(bookings))
print("Строк после merge:", len(df_final))
print("Число строк сохранилось:", len(bookings) == len(df_final))

# Проверка ключевых пропусков после объединения
print("\nПропуски после merge:")
print(df_final.isnull().sum())

# Проверка дублей по ключевой паре
print("\nДубли по passenger_id + flight_id после merge:",
      df_final.duplicated(subset=['passenger_id', 'flight_id']).sum())

# Проверка, все ли рейсы подтянулись
print("\nСтрок без данных о рейсе:",
      df_final['Номер рейса'].isnull().sum())

# Проверка, все ли пассажиры подтянулись
print("Строк без данных о пассажире:",
      df_final['Пол'].isnull().sum())

missing_flights = bookings.loc[
    ~bookings['flight_id'].isin(flights['flight_id']),
    'flight_id'
].nunique()

missing_passengers = bookings.loc[
    ~bookings['passenger_id'].isin(passengers['passenger_id']),
    'passenger_id'
].nunique()

print("flight_id из bookings, которых нет в flights:", missing_flights)
print("passenger_id из bookings, которых нет в passengers:", missing_passengers)

mask = df_final['Дата бронирования'] < df_final['Дата вылета']
print('Нарушения:', (~mask).sum())

mask = df_final['Аэропорт вылета'].astype(str).str.strip().str.upper() == df_final['Аэропорт прилета'].astype(str).str.strip().str.upper()
print('Совпадений аэропортов:', mask.sum())

"""# EDA"""

print("ОБЩАЯ ИНФОРМАЦИЯ")
print("Размер таблицы:", df_final.shape)
print("Количество пользователей:", df_final['passenger_id'].nunique())
print("Количество рейсов:", df_final['flight_id'].nunique())
print("Количество бронирований:", len(df_final))

df_final['Маршрут'] = df_final['Город вылета'] + ' → ' + df_final['Город прилета']

def plot_sparse_matrix(ax, df, user_col, item_col, title, top_n_users=200, top_n_items=200):
    top_users = df[user_col].value_counts().head(top_n_users).index
    top_items = df[item_col].value_counts().head(top_n_items).index

    df_plot = df[
        df[user_col].isin(top_users) &
        df[item_col].isin(top_items)
    ].copy()

    user_to_idx = {user: i for i, user in enumerate(top_users)}
    item_to_idx = {item: i for i, item in enumerate(top_items)}

    rows = df_plot[user_col].map(user_to_idx)
    cols = df_plot[item_col].map(item_to_idx)

    matrix = coo_matrix(
        (np.ones(len(df_plot)), (rows, cols)),
        shape=(len(top_users), len(top_items))
    )

    ax.spy(matrix, markersize=1)
    ax.set_title(title, fontsize=14)
    ax.set_xlabel('Объекты')
    ax.set_ylabel('Пассажиры')

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

plot_sparse_matrix(
    axes[0], df_final,
    user_col='passenger_id',
    item_col='flight_id',
    title='Пассажир – рейс (flight_id)'
)

plot_sparse_matrix(
    axes[1], df_final,
    user_col='passenger_id',
    item_col='Номер рейса',
    title='Пассажир – номер рейса'
)

plot_sparse_matrix(
    axes[2], df_final,
    user_col='passenger_id',
    item_col='Маршрут',
    title='Пассажир – маршрут'
)

plt.suptitle(
    'Разреженность матриц взаимодействий на разных уровнях представления',
    fontsize=18,
    y=1.02
)
plt.tight_layout()
plt.show()

def calc_sparsity(df, user_col, item_col, name):
    n_users = df[user_col].nunique()
    n_items = df[item_col].nunique()
    n_interactions = df[[user_col, item_col]].drop_duplicates().shape[0]

    density = n_interactions / (n_users * n_items)
    sparsity = 1 - density

    print(f"=== {name} ===")
    print(f"Пользователей: {n_users}")
    print(f"Объектов: {n_items}")
    print(f"Уникальных взаимодействий: {n_interactions}")
    print(f"Плотность матрицы: {density:.8f}")
    print(f"Разреженность матрицы: {sparsity:.6f}")
    print()

    return {
        "name": name,
        "n_users": n_users,
        "n_items": n_items,
        "n_interactions": n_interactions,
        "density": density,
        "sparsity": sparsity
    }

res_flight = calc_sparsity(df_final, 'passenger_id', 'flight_id', 'Пассажир – рейс (flight_id)')
res_number = calc_sparsity(df_final, 'passenger_id', 'Номер рейса', 'Пассажир – номер рейса')
res_route = calc_sparsity(df_final, 'passenger_id', 'Маршрут', 'Пассажир – маршрут')

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

plt.figure()
sns.countplot(
    data=df_final,
    x='Статус билета пассажира',
    order=df_final['Статус билета пассажира'].value_counts().index
)
plt.title('Распределение статусов билета')
plt.xlabel('Статус')
plt.ylabel('Количество')
plt.show()

plt.figure()
sns.countplot(
    data=df_final,
    x='Класс бронирования',
    order=df_final['Класс бронирования'].dropna().value_counts().index
)
plt.title('Распределение классов бронирования')
plt.xlabel('Класс бронирования')
plt.ylabel('Количество')
plt.show()

print("Пропуски в 'Класс бронирования':", df_final['Класс бронирования'].isna().sum())

plt.figure()
sns.countplot(
    data=df_final,
    x='Пол',
    order=df_final['Пол'].dropna().value_counts().index
)
plt.title('Распределение пассажиров по полу')
plt.xlabel('Пол')
plt.ylabel('Количество')
plt.show()

print("Пропуски в 'Пол':", df_final['Пол'].isna().sum())

plt.figure()
sns.countplot(
    data=df_final,
    x='Операционный перевозчик',
    order=df_final['Операционный перевозчик'].value_counts().index
)
plt.title('Распределение по операционным перевозчикам')
plt.xlabel('Перевозчик')
plt.ylabel('Количество')
plt.show()

top_dep = df_final['Город вылета'].value_counts().head(10).index
plt.figure()
sns.countplot(
    data=df_final[df_final['Город вылета'].isin(top_dep)],
    x='Город вылета',
    order=top_dep
)
plt.title('Топ-10 городов вылета')
plt.xlabel('Город вылета')
plt.ylabel('Количество')
plt.xticks(rotation=45)
plt.show()

top_arr = df_final['Город прилета'].value_counts().head(10).index
plt.figure()
sns.countplot(
    data=df_final[df_final['Город прилета'].isin(top_arr)],
    x='Город прилета',
    order=top_arr
)
plt.title('Топ-10 городов прилета')
plt.xlabel('Город прилета')
plt.ylabel('Количество')
plt.xticks(rotation=45)
plt.show()

top_airport_dep = df_final['Аэропорт вылета'].value_counts().head(10).index
plt.figure()
sns.countplot(
    data=df_final[df_final['Аэропорт вылета'].isin(top_airport_dep)],
    x='Аэропорт вылета',
    order=top_airport_dep
)
plt.title('Топ-10 аэропортов вылета')
plt.xlabel('Аэропорт вылета')
plt.ylabel('Количество')
plt.xticks(rotation=45)
plt.show()

top_airport_arr = df_final['Аэропорт прилета'].value_counts().head(10).index
plt.figure()
sns.countplot(
    data=df_final[df_final['Аэропорт прилета'].isin(top_airport_arr)],
    x='Аэропорт прилета',
    order=top_airport_arr
)
plt.title('Топ-10 аэропортов прилета')
plt.xlabel('Аэропорт прилета')
plt.ylabel('Количество')
plt.xticks(rotation=45)
plt.show()

birth_col = 'Дата рождения'
book_col = 'Дата бронирования'

# Приводим даты
df_final[birth_col] = pd.to_datetime(df_final[birth_col], errors='coerce').dt.tz_localize(None)
df_final[book_col]  = pd.to_datetime(df_final[book_col],  errors='coerce').dt.tz_localize(None)
df_final['Дата вылета'] = pd.to_datetime(df_final['Дата вылета'], errors='coerce').dt.tz_localize(None)
df_final['Маршрут'] = df_final['Город вылета'] + ' → ' + df_final['Город прилета']

# Считаем возраст ОДИН РАЗ на уровне passenger_id
# Берём одну строку на пассажира: самое раннее бронирование
passenger_base = (
    df_final.sort_values(book_col)
    .groupby('passenger_id', as_index=False)
    .first()[['passenger_id', birth_col, book_col]]
    .copy()
)

# age_days — возраст в днях от даты рождения до первого бронирования
passenger_base['дней_с_рождения_до_бронирования'] = (
    passenger_base[book_col] - passenger_base[birth_col]
).dt.days

# Возраст считаем по году первого бронирования
passenger_base['Возраст'] = (
    passenger_base[book_col].dt.year - passenger_base[birth_col].dt.year
    - (
        (passenger_base[book_col].dt.month < passenger_base[birth_col].dt.month) |
        (
            (passenger_base[book_col].dt.month == passenger_base[birth_col].dt.month) &
            (passenger_base[book_col].dt.day   < passenger_base[birth_col].dt.day)
        )
    ).astype(int)
).astype('Int64')

# Текстовое распределение ДО обработки
print("РАСПРЕДЕЛЕНИЕ ВОЗРАСТА ДО ОБРАБОТКИ")
age_raw = passenger_base['Возраст'].copy()
print(age_raw.describe())
print("Отрицательных:", (age_raw < 0).sum())
print("Нулевых по дням:", (passenger_base['дней_с_рождения_до_бронирования'] == 0).sum())
print("Пропусков:", age_raw.isna().sum())

# Очищаем некорректные значения на уровне пассажира
mask_zero_days = passenger_base['дней_с_рождения_до_бронирования'] == 0
mask_negative  = passenger_base['Возраст'] < 0
mask_bad_age   = mask_negative | mask_zero_days
passenger_base.loc[mask_bad_age, 'Возраст'] = np.nan

# Заполнение: по маршруту + классу, по маршруту, глобальной медианой
#    (берём медианы из df_final, там больше строк для расчёта)
group_cols = ['Маршрут', 'Класс бронирования']

# Замапим Маршрут и Класс на пассажира через первое бронирование
passenger_base2 = (
    df_final.sort_values(book_col)
    .groupby('passenger_id', as_index=False)
    .first()[['passenger_id', 'Маршрут', 'Класс бронирования']]
)
passenger_base = passenger_base.merge(passenger_base2, on='passenger_id', how='left')

# Медианы считаем по df_final (где уже есть все маршруты)
# Но Возраст там ещё не посчитан, поэтому считаем временно здесь же
age_med_group = (
    passenger_base.groupby(group_cols)['Возраст'].median()
)
age_med_route = (
    passenger_base.groupby('Маршрут')['Возраст'].median()
)
age_med_all = passenger_base['Возраст'].median()

def fill_age_row(row):
    if pd.isna(row['Возраст']):
        key = (row['Маршрут'], row['Класс бронирования'])
        if key in age_med_group.index and pd.notna(age_med_group.loc[key]):
            return age_med_group.loc[key]
        elif row['Маршрут'] in age_med_route.index and pd.notna(age_med_route.loc[row['Маршрут']]):
            return age_med_route.loc[row['Маршрут']]
        else:
            return age_med_all
    return row['Возраст']

passenger_base['Возраст'] = passenger_base.apply(fill_age_row, axis=1)
passenger_base['Возраст'] = passenger_base['Возраст'].round().astype('Int64')

# Синхронизируем дату рождения для исправленных
mask_age_fixed = mask_bad_age & passenger_base['Возраст'].notna()

new_birth_year = (
    passenger_base.loc[mask_age_fixed, book_col].dt.year
    - passenger_base.loc[mask_age_fixed, 'Возраст']
)
old_birth = passenger_base.loc[mask_age_fixed, birth_col]

passenger_base.loc[mask_age_fixed, birth_col] = pd.to_datetime(
    dict(
        year=new_birth_year,
        month=old_birth.dt.month.fillna(6).astype(int),
        day=old_birth.dt.day.fillna(15).astype(int)
    ),
    errors='coerce'
)

# Мержим ОДНО значение возраста и дату рождения обратно в df_final
age_map = passenger_base[['passenger_id', 'Возраст', birth_col]].copy()
age_map = age_map.rename(columns={birth_col: birth_col + '_fixed'})

df_final = df_final.drop(columns=['Возраст', birth_col], errors='ignore')
df_final = df_final.merge(age_map, on='passenger_id', how='left')
df_final = df_final.rename(columns={birth_col + '_fixed': birth_col})

# age_days_at_booking тоже на уровне пассажира
age_days_map = passenger_base[['passenger_id', 'дней_с_рождения_до_бронирования']]
df_final = df_final.drop(columns=['дней_с_рождения_до_бронирования'], errors='ignore')
df_final = df_final.merge(age_days_map, on='passenger_id', how='left')

# Статистика ПОСЛЕ и график распределения
print("СТАТИСТИКА ВОЗРАСТА ПОСЛЕ ОБРАБОТКИ И СИНХРОНИЗАЦИИ")
print(df_final['Возраст'].describe())
print(f"Пропусков осталось: {df_final['Возраст'].isna().sum()}")

plt.figure(figsize=(10, 5))
sns.histplot(df_final['Возраст'].dropna(), bins=20, kde=True)
plt.title('Распределение возраста ПОСЛЕ обработки и синхронизации с датой рождения')
plt.xlabel('Возраст')
plt.ylabel('Количество')
plt.show()

zero_age_passengers = passenger_base[passenger_base['Возраст'] == 0]
print("Уникальных пассажиров с возрастом 0:", zero_age_passengers['passenger_id'].nunique())

print("ВРЕМЕННЫЕ ХАРАКТЕРИСТИКИ")

print("\nДиапазон бронирований:")
print(df_final['Дата бронирования'].agg(['min', 'max']))

print("\nДиапазон вылетов:")
print(df_final['Дата вылета'].agg(['min', 'max']))

print("\nБронирования по годам:")
print(df_final['Дата бронирования'].dt.year.value_counts().sort_index())

print("\nБронирования по месяцам:")
print(df_final['Дата бронирования'].dt.month.value_counts().sort_index())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# По годам
year_counts = df_final['Дата бронирования'].dt.year.value_counts().sort_index()
axes[0].bar(year_counts.index.astype(str), year_counts.values)
axes[0].set_title('Распределение бронирований по годам')
axes[0].set_xlabel('Год')
axes[0].set_ylabel('Количество бронирований')

# По месяцам
month_counts = df_final['Дата бронирования'].dt.month.value_counts().sort_index()
axes[1].bar(month_counts.index, month_counts.values)
axes[1].set_title('Распределение бронирований по месяцам')
axes[1].set_xlabel('Месяц')
axes[1].set_ylabel('Количество бронирований')
axes[1].set_xticks(range(1, 13))

plt.tight_layout()
plt.show()

print("СТРУКТУРА ВЗАИМОДЕЙСТВИЙ")

n_users = df_final['passenger_id'].nunique()
n_items = df_final['flight_id'].nunique()
n_interactions = len(df_final)

sparsity = 1 - (n_interactions / (n_users * n_items))

print("Пользователи:", n_users)
print("Рейсы:", n_items)
print("Взаимодействия:", n_interactions)
print(f"Разреженность матрицы взаимодействий: {sparsity:.6f}")

print("ПОПУЛЯРНЫЕ МАРШРУТЫ")

df_final['Маршрут'] = df_final['Город вылета'] + " → " + df_final['Город прилета']
print(df_final['Маршрут'].value_counts().head(10))

top10 = df_final['Маршрут'].value_counts().head(10)
plt.figure(figsize=(10, 5))
sns.barplot(x=top10.values, y=top10.index)
plt.title('Топ-10 маршрутов по количеству бронирований')
plt.xlabel('Количество бронирований')
plt.ylabel('Маршрут')
plt.tight_layout()
plt.show()

import pandas as pd

# считаем количество бронирований для каждой пары (город вылета, город прилета)
route_counts = df_final.groupby(['Город вылета', 'Город прилета']).size()

# сколько маршрутов встречается 1 раз, 2 раза, 3 раза и т.д.
counts = route_counts.value_counts().sort_index()

# доля маршрутов с каждой частотой, %
shares = (route_counts.value_counts(normalize=True) * 100).round(2)

print("Распределение маршрутов по частоте (кол-во бронирований → доля маршрутов, %):")
print(pd.DataFrame({
    "count": counts.index,
    "num_routes": counts.values,
    "share_%": shares.values
}))

sns.set(style="whitegrid")

# Число бронирований на пользователя
user_activity = df_final.groupby('passenger_id').size()

print("Статистика по числу бронирований на пользователя:")
print(user_activity.describe())

share_1 = (user_activity == 1).mean() * 100
share_2_plus = (user_activity >= 2).mean() * 100
share_5_plus = (user_activity >= 5).mean() * 100

print(f"Доля пользователей с 1 бронированием: {share_1:.2f}%")
print(f"Доля пользователей с 2 и более бронированиями: {share_2_plus:.2f}%")
print(f"Доля пользователей с 5 и более бронированиями: {share_5_plus:.2f}%")

# Число уникальных маршрутов на пользователя
user_routes_unique = df_final.groupby('passenger_id')['Маршрут'].nunique()

print("Статистика по числу уникальных маршрутов на пользователя:")
print(user_routes_unique.describe())

share_1_routes = (user_routes_unique == 1).mean() * 100
share_2_plus_routes = (user_routes_unique >= 2).mean() * 100
share_5_plus_routes = (user_routes_unique >= 5).mean() * 100

print(f"Доля пользователей с 1 уникальным маршрутом: {share_1_routes:.2f}%")
print(f"Доля пользователей с 2 и более уникальными маршрутами: {share_2_plus_routes:.2f}%")
print(f"Доля пользователей с 5 и более уникальными маршрутами: {share_5_plus_routes:.2f}%")

# ОДНА фигура с двумя графиками
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Слева: распределение числа бронирований
sns.countplot(x=user_activity, ax=axes[0])
axes[0].set_title('Число бронирований на пользователя')
axes[0].set_xlabel('Число бронирований')
axes[0].set_ylabel('Количество пользователей')

# Справа: распределение числа уникальных маршрутов
sns.countplot(x=user_routes_unique, ax=axes[1])
axes[1].set_title('Число уникальных маршрутов на пользователя')
axes[1].set_xlabel('Число уникальных маршрутов')
axes[1].set_ylabel('Количество пользователей')

plt.tight_layout()
plt.show()

sns.set(style="whitegrid", font_scale=1.1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# задаём свои цвета для полов
palette_sex = {0: '#4C72B0',  # синий
               1: '#bdbdbd'}  # серый

# Слева: гистограмма возраста по полу (stack)
sns.histplot(
    data=df_final,
    x='Возраст',
    bins=20,
    hue='Пол',
    multiple='stack',
    ax=axes[0],
    palette=palette_sex,
    alpha=0.8
)
axes[0].set_title("Распределение возраста по полу")
axes[0].set_xlabel("Возраст")
axes[0].set_ylabel("Количество пассажиров")

# Справа: распределение по полу
sns.countplot(
    data=df_final,
    x='Пол',
    hue='Пол',
    dodge=False,
    order=df_final['Пол'].dropna().value_counts().index,
    ax=axes[1],
    palette=palette_sex,
    legend=False
)
axes[1].set_title('Распределение пассажиров по полу')
axes[1].set_xlabel('Пол')
axes[1].set_ylabel('Количество')

plt.tight_layout()
plt.show()

df_final.head(3)

"""# Формирование итогового датасета"""

df_final.info()

df = df_final.copy()

df['dow'] = df['Дата вылета'].dt.dayofweek
df['month'] = df['Дата вылета'].dt.month
df['hour'] = df['Дата вылета'].dt.hour

def time_of_day(h):
    if 5 <= h < 11:
        return 'утро'
    elif 12 <= h < 17:
        return 'день'
    elif 17 <= h < 22:
        return 'вечер'
    else:
        return 'ночь'

df['time_of_day'] = df['hour'].apply(time_of_day)

# Лаг между бронированием и вылетом
df['days_before_departure'] = (
    df['Дата вылета'] - df['Дата бронирования']
).dt.days

# самый частый город в списке
dep_cities = df.groupby('passenger_id')['Город вылета'].apply(list)
arr_cities = df.groupby('passenger_id')['Город прилета'].apply(list)

all_cities = (dep_cities + arr_cities).rename('all_cities')

def most_frequent_city(cities):
    if not cities:
        return np.nan
    return pd.Series(cities).value_counts().idxmax()

# Удобный город (самый частый общий город для пассажира)
home_city = all_cities.apply(most_frequent_city).rename('Удобный город')
df = df.merge(home_city, on='passenger_id', how='left')

# Кол-во уникальных маршрутов на пассажира
n_unique_routes = (
    df.groupby('passenger_id')['Маршрут'].nunique()
      .rename('n_unique_routes')
)

df = df.merge(n_unique_routes, on='passenger_id', how='left')

# Категоризация окна бронирования:
# <= 6        -> last_minute
# 7–30        -> short_advance
# 31–180      -> medium_advance
# > 180       -> long_advance

def booking_window_category(d):
    if d <= 6:
        return 'last_minute'
    elif d <= 30:
        return 'short_advance'
    elif d <= 180:
        return 'medium_advance'
    else:
        return 'long_advance'

df['booking_window_cat'] = df['days_before_departure'].apply(booking_window_category)


cols_to_drop = [
    'Дата рождения',
    'дней_с_рождения_до_бронирования',
    # 'Дата бронирования',
    # 'Дата вылета',
    'days_before_departure',
    'Операционный перевозчик'
]

df.drop(columns=[c for c in cols_to_drop if c in df.columns],
        inplace=True)

df = df.drop(columns=['hour'], errors='ignore')

def month_to_season(m):
    if m in [12, 1, 2]:
        return 'зима'
    elif m in [3, 4, 5]:
        return 'весна'
    elif m in [6, 7, 8]:
        return 'лето'
    else:
        return 'осень'

df['season'] = df['month'].apply(month_to_season)

df = df.drop(columns=['month'], errors='ignore')

def dow_category(d):
    if d in [0, 1]:
        return 'начало_недели'
    elif d in [2, 3]:
        return 'середина_недели'
    else:
        return 'выходные'

df['dow_cat'] = df['dow'].apply(dow_category)

df = df.drop(columns=['dow'], errors='ignore')

# Число бронирований на пользователя
user_bookings = (
    df.groupby('passenger_id')
      .size()
      .rename('user_total_bookings')
)

df = df.merge(user_bookings, on='passenger_id', how='left')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

sns.countplot(data=df, x='time_of_day', ax=axes[0])
axes[0].set_title('Распределение по времени суток')

sns.countplot(data=df, x='season', ax=axes[1])
axes[1].set_title('Распределение по сезонам')

sns.countplot(data=df, x='dow_cat', ax=axes[2])
axes[2].set_title('Распределение по дням недели')

for ax in axes:
    ax.set_xlabel('')
    ax.set_ylabel('Количество бронирований')

plt.tight_layout()
plt.show()

import pandas as pd

df_tmp = df.sort_values(['passenger_id', 'Дата вылета']).copy()

# --- Любимое время суток для каждого пользователя ---
fav_tod = (
    df_tmp.groupby('passenger_id')['time_of_day']
          .agg(lambda x: x.value_counts().idxmax())
          .rename('fav_time_of_day')
)

# --- Любимый сезон ---
fav_season = (
    df_tmp.groupby('passenger_id')['season']
          .agg(lambda x: x.value_counts().idxmax())
          .rename('fav_season')
)

# --- Любимая категория дня недели ---
fav_dow = (
    df_tmp.groupby('passenger_id')['dow_cat']
          .agg(lambda x: x.value_counts().idxmax())
          .rename('fav_dow_cat')
)

# Берём последний вылет каждого пассажира
last_flight = (
    df_tmp.groupby('passenger_id')
          .tail(1)[['passenger_id', 'time_of_day', 'season', 'dow_cat']]
          .set_index('passenger_id')
)

# Объединяем
prefs = pd.concat([fav_tod, fav_season, fav_dow], axis=1).join(last_flight)

# Считаем, совпадает ли последний вылет с "любимым" паттерном
prefs['same_tod'] = prefs['fav_time_of_day'] == prefs['time_of_day']
prefs['same_season'] = prefs['fav_season'] == prefs['season']
prefs['same_dow'] = prefs['fav_dow_cat'] == prefs['dow_cat']

share_same_tod = prefs['same_tod'].mean() * 100
share_same_season = prefs['same_season'].mean() * 100
share_same_dow = prefs['same_dow'].mean() * 100

print(f"Доля пользователей, у которых последний вылет совпадает с преобладающим временем суток: {share_same_tod:.2f}%")
print(f"Доля пользователей, у которых последний вылет совпадает с преобладающим сезоном: {share_same_season:.2f}%")
print(f"Доля пользователей, у которых последний вылет совпадает с преобладающей категорией дня недели: {share_same_dow:.2f}%")

import pandas as pd

# --- Прилёты в Москву ---
df_arr_mow = df[df['Город прилета'] == 'MOW'].copy()
df_arr_mow = df_arr_mow.sort_values(['passenger_id', 'Дата вылета'])

print("Записей с прилётом в Москву:", len(df_arr_mow))

# любимый аэропорт прилёта в Москве
fav_arr_airport = (
    df_arr_mow.groupby('passenger_id')['Аэропорт прилета']
              .agg(lambda x: x.value_counts().idxmax())
              .rename('fav_arr_mow_airport')
)

# аэропорт последнего прилёта в Москву
last_arr_mow = (
    df_arr_mow.groupby('passenger_id')
              .tail(1)[['passenger_id', 'Аэропорт прилета']]
              .set_index('passenger_id')
              .rename(columns={'Аэропорт прилета': 'last_arr_mow_airport'})
)

arr_prefs = fav_arr_airport.to_frame().join(last_arr_mow)

arr_prefs['same_arr_airport'] = (
    arr_prefs['fav_arr_mow_airport'] == arr_prefs['last_arr_mow_airport']
)

share_same_arr = arr_prefs['same_arr_airport'].mean() * 100

print(f"\nДоля пассажиров, у которых последний прилёт в Москву совпадает с преобладающим московским аэропортом прилёта: {share_same_arr:.2f}%")

print("\nПреобладающие московские аэропорты прилёта по пассажирам (%):")
print(arr_prefs['fav_arr_mow_airport'].value_counts(normalize=True).mul(100).round(2))


# --- Вылеты из Москвы ---
df_dep_mow = df[df['Город вылета'] == 'MOW'].copy()
df_dep_mow = df_dep_mow.sort_values(['passenger_id', 'Дата вылета'])

print("\nЗаписей с вылетом из Москвы:", len(df_dep_mow))

# любимый аэропорт вылета в Москве
fav_dep_airport = (
    df_dep_mow.groupby('passenger_id')['Аэропорт вылета']
              .agg(lambda x: x.value_counts().idxmax())
              .rename('fav_dep_mow_airport')
)

# аэропорт последнего вылета из Москвы
last_dep_mow = (
    df_dep_mow.groupby('passenger_id')
              .tail(1)[['passenger_id', 'Аэропорт вылета']]
              .set_index('passenger_id')
              .rename(columns={'Аэропорт вылета': 'last_dep_mow_airport'})
)

dep_prefs = fav_dep_airport.to_frame().join(last_dep_mow)

dep_prefs['same_dep_airport'] = (
    dep_prefs['fav_dep_mow_airport'] == dep_prefs['last_dep_mow_airport']
)

share_same_dep = dep_prefs['same_dep_airport'].mean() * 100

print(f"\nДоля пассажиров, у которых последний вылет из Москвы совпадает с преобладающим московским аэропортом вылета: {share_same_dep:.2f}%")

print("\nПреобладающие московские аэропорты вылета по пассажирам (%):")
print(dep_prefs['fav_dep_mow_airport'].value_counts(normalize=True).mul(100).round(2))

df.to_csv('df.csv', index=False)

"""# Формирование графового представления данных"""

import networkx as nx

# Узлы-пассажиры
passenger_nodes = df[
    ['passenger_id', 'Пол', 'Возраст', 'user_total_bookings',
     'Удобный город', 'n_unique_routes']
].drop_duplicates(subset=['passenger_id']).copy()

passenger_nodes['node_type'] = 'passenger'

print("Узлы-пассажиры:", passenger_nodes.shape)
passenger_nodes.tail(3)

flight_nodes = df[
    [
        'flight_id',
        'Номер рейса',
        'Город вылета',
        'Город прилета',
        'Аэропорт вылета',
        'Аэропорт прилета',
        'Маршрут',
        'season',
        'time_of_day',
        'dow_cat'
    ]
].drop_duplicates(subset=['flight_id']).copy()

flight_nodes['node_type'] = 'flight'

print("Узлы-рейсы:", flight_nodes.shape)
flight_nodes.tail(3)

edges = df[
    [
        'passenger_id',
        'flight_id',
        'Статус билета пассажира',
        'Класс бронирования',
        'booking_window_cat',
        'time_of_day',
        'dow_cat'
    ]
].drop_duplicates(subset=['passenger_id', 'flight_id']).copy()

edges['edge_type'] = 'booking'
edges['weight'] = 1

print("Рёбра:", edges.shape)
edges.head(3)

B_full = nx.Graph()

# Узлы-пассажиры
for _, row in passenger_nodes.iterrows():
    B_full.add_node(
        f"passenger_{row['passenger_id']}",
        bipartite='passenger',
        passenger_id=int(row['passenger_id']),
        sex=int(row['Пол']),                     # если 0/1; если 'M'/'F' — не int
        age=int(row['Возраст']) if pd.notna(row['Возраст']) else -1,
        user_total_bookings=int(row['user_total_bookings']),
        home_city=row['Удобный город'],
        n_unique_routes=int(row['n_unique_routes']),
    )

# Узлы-рейсы
for _, row in flight_nodes.iterrows():
    B_full.add_node(
        f"flight_{row['flight_id']}",
        bipartite='flight',
        flight_id=int(row['flight_id']),
        flight_number=int(row['Номер рейса']),
        dep_city=row['Город вылета'],
        arr_city=row['Город прилета'],
        dep_airport=row['Аэропорт вылета'],
        arr_airport=row['Аэропорт прилета'],
        route=row['Маршрут'],
        season=row['season'],
        time_of_day=row['time_of_day'],
        dow_cat=row['dow_cat'],
    )


# Рёбра пассажир–рейс
for _, row in edges.iterrows():
    B_full.add_edge(
        f"passenger_{row['passenger_id']}",
        f"flight_{row['flight_id']}",
        edge_type='booking',
        ticket_status=row['Статус билета пассажира'],
        booking_class=row['Класс бронирования'],
        booking_window_cat=row['booking_window_cat'],
        time_of_day=row['time_of_day'],
        dow_cat=row['dow_cat'],
        weight=1
    )

print("ХАРАКТЕРИСТИКИ ГРАФА")
print("Число узлов:", B_full.number_of_nodes())
print("Число рёбер:", B_full.number_of_edges())

passenger_count = sum(1 for _, d in B_full.nodes(data=True) if d['bipartite'] == 'passenger')
flight_count = sum(1 for _, d in B_full.nodes(data=True) if d['bipartite'] == 'flight')

print("Число узлов-пассажиров:", passenger_count)
print("Число узлов-рейсов:", flight_count)

print("Граф двудольный:", nx.algorithms.bipartite.is_bipartite(B_full))

user_id = 7207685090102411267
print(f"Анализируем пользователя: {user_id}")

user_flights = df[df['passenger_id'] == user_id][
    ['flight_id', 'Маршрут', 'Класс бронирования', 'season', 'time_of_day', 'dow_cat']
].copy()

print(f"Бронирований: {len(user_flights)}")

G = nx.Graph()
G.add_node("User", size=1000)

flight_nodes = []
for _, row in user_flights.iterrows():
    label = f"{row['Маршрут']}\n{row['Класс бронирования']}, {row['season']}, {row['time_of_day']}"
    node_id = f"F{row['flight_id']}"
    G.add_node(node_id, label=label, size=800)
    G.add_edge("User", node_id)
    flight_nodes.append(node_id)


plt.figure(figsize=(12, 8))

pos = nx.spring_layout(G, k=2, iterations=30)

# готовим подписи: для User просто 'User', для рейсов — label из атрибутов
labels = {}
for n, d in G.nodes(data=True):
    if n == "User":
        labels[n] = f"User {user_id}"
    else:
        labels[n] = d.get('label', n)

colors = ['lightblue'] + ['lightcoral'] * len(flight_nodes)
sizes = [1200] + [800] * len(flight_nodes)

nx.draw(
    G, pos,
    node_color=colors,
    node_size=sizes,
    with_labels=False,
    edge_color='gray',
    width=2,
    alpha=0.9
)

nx.draw_networkx_labels(G, pos, labels, font_size=8, font_weight='bold')

plt.title(
    f"Профиль пользователя {user_id}\n"
    f"{len(user_flights)} рейсов, "
    f"{user_flights['Маршрут'].nunique()} уникальных маршрутов",
    fontsize=14,
    pad=20
)
plt.tight_layout()
plt.show()

flight_user_counts = (
    df.groupby('Номер рейса')['passenger_id']
      .nunique()
      .sort_values(ascending=False)
)

# можно выбрать вручную, а можно самый популярный
target_flight_number = flight_user_counts.index[0]

users_for_flight = (
    df[df['Номер рейса'] == target_flight_number]['passenger_id']
    .drop_duplicates()
    .head(5)
    .tolist()
)

sample = df[df['passenger_id'].isin(users_for_flight)].copy()

# агрегируем passenger - flight_number по всем рейсам
agg = (
    sample.groupby(['passenger_id', 'Номер рейса'])
          .size()
          .reset_index(name='cnt')
)

G = nx.Graph()

# отображение passenger_id → P1..P5
user_map = {user: f"P{i+1}" for i, user in enumerate(users_for_flight)}

# узлы-пассажиры
for user in users_for_flight:
    G.add_node(
        user_map[user],
        kind='passenger',
        passenger_id=user
    )

# узлы-номера рейсов (все, на которых летали эти 5 пассажиров)
for fn in sorted(agg['Номер рейса'].unique()):
    G.add_node(
        f"R{fn}",
        kind='flight_number',
        flight_number=fn
    )

# рёбра: связь пассажир ↔ любой номер рейса, по которому он летал
for _, row in agg.iterrows():
    G.add_edge(
        user_map[row['passenger_id']],
        f"R{row['Номер рейса']}",
        weight=row['cnt']
    )

# 5. Визуализация

passenger_nodes = [n for n, d in G.nodes(data=True) if d['kind'] == 'passenger']
flight_nodes    = [n for n, d in G.nodes(data=True) if d['kind'] == 'flight_number']

# позиционируем в две колонки
pos = {}
for i, n in enumerate(passenger_nodes):
    pos[n] = (0, i * 2)
for i, n in enumerate(flight_nodes):
    pos[n] = (3, i * (len(passenger_nodes) * 2 / max(1, len(flight_nodes))))

plt.figure(figsize=(11, 7))

weights = [1.5 + 1.2 * d['weight'] for _, _, d in G.edges(data=True)]

# узлы
p_nodes = nx.draw_networkx_nodes(
    G, pos,
    nodelist=passenger_nodes,
    node_color='steelblue',
    node_size=1600,
    label='Пассажиры'
)
f_nodes = nx.draw_networkx_nodes(
    G, pos,
    nodelist=flight_nodes,
    node_color='orange',
    node_size=900,
    label='Номера рейсов'
)

# рёбра
nx.draw_networkx_edges(
    G, pos,
    width=weights,
    alpha=0.6,
    edge_color='gray'
)

# подписи P1..P5, Rxxxx
nx.draw_networkx_labels(
    G, pos,
    font_size=8,
    font_weight='bold'
)

# заголовок
plt.title(
    f"Двудольный граф «Пассажиры ↔ Номера рейсов»",
    fontsize=14
)
plt.axis('off')

# легенда СБОКУ
legend = plt.legend(
    handles=[p_nodes, f_nodes],
    labels=['Пассажиры', 'Номера рейсов'],
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    fontsize=10,
    frameon=True
)
legend.get_frame().set_alpha(0.9)

plt.tight_layout()
plt.show()

sample_route = df[df['passenger_id'].isin(users_for_flight)].copy()

agg_r = (
    sample_route.groupby(['passenger_id', 'Маршрут'])
                .size()
                .reset_index(name='cnt')
)

G_route = nx.Graph()

# отображение passenger_id → P1..P5 (та же нумерация, что и в графе по рейсам)
user_map = {user: f"P{i+1}" for i, user in enumerate(users_for_flight)}

# узлы-пассажиры
for user in users_for_flight:
    G_route.add_node(
        user_map[user],
        kind='passenger',
        passenger_id=user
    )

# узлы-маршруты (все, по которым летали эти 5 пассажиров)
for r in sorted(agg_r['Маршрут'].unique()):
    G_route.add_node(
        f"M{r}",
        kind='route',
        route=r
    )

# рёбра: связь пассажир ↔ маршрут
for _, row in agg_r.iterrows():
    G_route.add_edge(
        user_map[row['passenger_id']],
        f"M{row['Маршрут']}",
        weight=row['cnt']
    )

passenger_nodes = [n for n, d in G_route.nodes(data=True) if d['kind'] == 'passenger']
route_nodes     = [n for n, d in G_route.nodes(data=True) if d['kind'] == 'route']

# позиционируем в две колонки
pos = {}
for i, n in enumerate(passenger_nodes):
    pos[n] = (0, i * 2)
for i, n in enumerate(route_nodes):
    pos[n] = (3, i * (len(passenger_nodes) * 2 / max(1, len(route_nodes))))

plt.figure(figsize=(11, 7))

weights = [1.5 + 1.2 * d['weight'] for _, _, d in G_route.edges(data=True)]

# узлы
p_nodes = nx.draw_networkx_nodes(
    G_route, pos,
    nodelist=passenger_nodes,
    node_color='steelblue',
    node_size=1600,
    label='Пассажиры'
)
r_nodes = nx.draw_networkx_nodes(
    G_route, pos,
    nodelist=route_nodes,
    node_color='lightgreen',
    node_size=900,
    label='Маршруты'
)

# рёбра
nx.draw_networkx_edges(
    G_route, pos,
    width=weights,
    alpha=0.6,
    edge_color='gray'
)

# подписи P1..P5 и маршруты вида "SVX → ASF"
nx.draw_networkx_labels(
    G_route, pos,
    font_size=7,
    font_weight='bold'
)

# заголовок
plt.title(
    "Двудольный граф «Пассажиры ↔ Маршруты»",
    fontsize=14
)
plt.axis('off')

# легенда сбоку
legend = plt.legend(
    handles=[p_nodes, r_nodes],
    labels=['Пассажиры', 'Маршруты'],
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    fontsize=10,
    frameon=True
)
legend.get_frame().set_alpha(0.9)

plt.tight_layout()
plt.show()

